spring:
   application:
            name: user-service
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      hikari: 
            idle-timeout: 300000
            minimum-idle: 1
 
   jpa:
      properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
  
      hibernate:
               ddl-auto: none
      show-sql: true

server:
      port: 0
      #port: 8085

eureka:
    instance:
         instance-id: ${spring.application.name}:${random.uuid}