spring:
      application:
            name: discovery-server

server:
   port: 8766
   servlet:
         context-path: /

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
             defaultZone: http://localhost:8766/eureka/
      region: default