spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      hikari: 
            idle-timeout: 300000
            minimum-idle: 1
 
   jpa:
      properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
  
      hibernate:
               ddl-auto: none
      show-sql: true
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8766/eureka
    registerWithEureka: true
    fetchRegistry: true