spring:
      application:
                 name: config-server
      profiles: 
                active: native
      cloud:
           config:
                 server:
                       native:
                            searchLocations: file:..\\..\\..\\..\\configs

server:
      port: 8888

eureka:
    instance:
         instanceId: ${spring.application.name}:${random.uuid}