spring:
      application:
                 name: config-server
      profiles: 
                active: native
      security:
            basic:
                enabled: true
      cloud:
           config:
                 server:
                       native:
                            searchLocations: file:..\\..\\..\\..\\configs
           security:
                 user:
                     name: admin
                     password: password


server:
      port: 0
      servlet:
             context-path: /

eureka:
    instance:
         instanceId: ${spring.application.name}:${random.uuid}
    client:
         serviceUrl:
            defaultZone: http://localhost:8766/eureka
         registerWithEureka: true
         fetchRegistry: false
         region: default
