spring:
      application:
                 name: config-server
      profiles: 
                active: native
      cloud:
           config:
                 server:
                       native:
                            searchLocations: file:..\\..\\..\\..\\configs

server:
      port: 0

eureka:
    instance:
         instanceId: ${spring.application.name}:${random.uuid}
    client:
         serviceUrl:
            defaultZone: http://localhost:8766/eureka
         registerWithEureka: true
         fetchRegistry: false
